version: '3.7'
services:
  database:
    image: postgres:alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapp:
    depends_on:
      - database
    image: dotcross:latest
    ports:
      - "9090:9090"
    environment:
      DB_URL: "database"

